<?php

/**
 * BaseSubscriptionCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_profile_id
 * @property integer $category_id
 * @property SfGuardUserProfile $SfGuardUserProfile
 * @property Category $Category
 * 
 * @method integer              getUserProfileId()      Returns the current record's "user_profile_id" value
 * @method integer              getCategoryId()         Returns the current record's "category_id" value
 * @method SfGuardUserProfile   getSfGuardUserProfile() Returns the current record's "SfGuardUserProfile" value
 * @method Category             getCategory()           Returns the current record's "Category" value
 * @method SubscriptionCategory setUserProfileId()      Sets the current record's "user_profile_id" value
 * @method SubscriptionCategory setCategoryId()         Sets the current record's "category_id" value
 * @method SubscriptionCategory setSfGuardUserProfile() Sets the current record's "SfGuardUserProfile" value
 * @method SubscriptionCategory setCategory()           Sets the current record's "Category" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSubscriptionCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscription_category');
        $this->hasColumn('user_profile_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUserProfile', array(
             'local' => 'user_profile_id',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}