<?php

/**
 * BaseProposalHasCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $proposal_id
 * @property integer $category_id
 * @property Category $Category
 * @property Proposal $Proposal
 * 
 * @method integer             getProposalId()  Returns the current record's "proposal_id" value
 * @method integer             getCategoryId()  Returns the current record's "category_id" value
 * @method Category            getCategory()    Returns the current record's "Category" value
 * @method Proposal            getProposal()    Returns the current record's "Proposal" value
 * @method ProposalHasCategory setProposalId()  Sets the current record's "proposal_id" value
 * @method ProposalHasCategory setCategoryId()  Sets the current record's "category_id" value
 * @method ProposalHasCategory setCategory()    Sets the current record's "Category" value
 * @method ProposalHasCategory setProposal()    Sets the current record's "Proposal" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProposalHasCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proposal_has_category');
        $this->hasColumn('proposal_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Proposal', array(
             'local' => 'proposal_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}