<?php

/**
 * BaseSfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $nickname
 * @property integer $gender
 * @property string $telephone
 * @property string $address
 * @property string $postal_code
 * @property string $location
 * @property string $province
 * @property string $country
 * @property string $web
 * @property clob $about
 * @property boolean $subscription_email
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $categories
 * @property Doctrine_Collection $regions
 * @property Doctrine_Collection $SubscriptionRegion
 * @property Doctrine_Collection $SubscriptionCategory
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getUserId()               Returns the current record's "user_id" value
 * @method string              getNickname()             Returns the current record's "nickname" value
 * @method integer             getGender()               Returns the current record's "gender" value
 * @method string              getTelephone()            Returns the current record's "telephone" value
 * @method string              getAddress()              Returns the current record's "address" value
 * @method string              getPostalCode()           Returns the current record's "postal_code" value
 * @method string              getLocation()             Returns the current record's "location" value
 * @method string              getProvince()             Returns the current record's "province" value
 * @method string              getCountry()              Returns the current record's "country" value
 * @method string              getWeb()                  Returns the current record's "web" value
 * @method clob                getAbout()                Returns the current record's "about" value
 * @method boolean             getSubscriptionEmail()    Returns the current record's "subscription_email" value
 * @method sfGuardUser         getSfGuardUser()          Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getCategories()           Returns the current record's "categories" collection
 * @method Doctrine_Collection getRegions()              Returns the current record's "regions" collection
 * @method Doctrine_Collection getSubscriptionRegion()   Returns the current record's "SubscriptionRegion" collection
 * @method Doctrine_Collection getSubscriptionCategory() Returns the current record's "SubscriptionCategory" collection
 * @method SfGuardUserProfile  setId()                   Sets the current record's "id" value
 * @method SfGuardUserProfile  setUserId()               Sets the current record's "user_id" value
 * @method SfGuardUserProfile  setNickname()             Sets the current record's "nickname" value
 * @method SfGuardUserProfile  setGender()               Sets the current record's "gender" value
 * @method SfGuardUserProfile  setTelephone()            Sets the current record's "telephone" value
 * @method SfGuardUserProfile  setAddress()              Sets the current record's "address" value
 * @method SfGuardUserProfile  setPostalCode()           Sets the current record's "postal_code" value
 * @method SfGuardUserProfile  setLocation()             Sets the current record's "location" value
 * @method SfGuardUserProfile  setProvince()             Sets the current record's "province" value
 * @method SfGuardUserProfile  setCountry()              Sets the current record's "country" value
 * @method SfGuardUserProfile  setWeb()                  Sets the current record's "web" value
 * @method SfGuardUserProfile  setAbout()                Sets the current record's "about" value
 * @method SfGuardUserProfile  setSubscriptionEmail()    Sets the current record's "subscription_email" value
 * @method SfGuardUserProfile  setSfGuardUser()          Sets the current record's "sfGuardUser" value
 * @method SfGuardUserProfile  setCategories()           Sets the current record's "categories" collection
 * @method SfGuardUserProfile  setRegions()              Sets the current record's "regions" collection
 * @method SfGuardUserProfile  setSubscriptionRegion()   Sets the current record's "SubscriptionRegion" collection
 * @method SfGuardUserProfile  setSubscriptionCategory() Sets the current record's "SubscriptionCategory" collection
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'unique' => true,
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nickname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gender', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('telephone', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('postal_code', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('location', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('province', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('country', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('web', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('about', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('subscription_email', 'boolean', null, array(
             'default' => 0,
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Category as categories', array(
             'refClass' => 'SubscriptionCategory',
             'local' => 'user_profile_id',
             'foreign' => 'category_id'));

        $this->hasMany('Region as regions', array(
             'refClass' => 'SubscriptionRegion',
             'local' => 'user_profile_id',
             'foreign' => 'region_id'));

        $this->hasMany('SubscriptionRegion', array(
             'local' => 'id',
             'foreign' => 'user_profile_id'));

        $this->hasMany('SubscriptionCategory', array(
             'local' => 'id',
             'foreign' => 'user_profile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $geographical0 = new Doctrine_Template_Geographical();
        $this->actAs($timestampable0);
        $this->actAs($geographical0);
    }
}