<?php

/**
 * BaseContentHasRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $region_id
 * @property string $type
 * @property Region $Region
 * 
 * @method integer          getContentId()  Returns the current record's "content_id" value
 * @method integer          getRegionId()   Returns the current record's "region_id" value
 * @method string           getType()       Returns the current record's "type" value
 * @method Region           getRegion()     Returns the current record's "Region" value
 * @method ContentHasRegion setContentId()  Sets the current record's "content_id" value
 * @method ContentHasRegion setRegionId()   Sets the current record's "region_id" value
 * @method ContentHasRegion setType()       Sets the current record's "type" value
 * @method ContentHasRegion setRegion()     Sets the current record's "Region" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContentHasRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_has_region');
        $this->hasColumn('content_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 100, array(
             'primary' => true,
             'type' => 'string',
             'length' => 100,
             ));


        $this->index('IX_ContentHasRegion_1', array(
             'fields' => 
             array(
              0 => 'region_id',
              1 => 'content_id',
              2 => 'type',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}