<?php

/**
 * BaseProposalHasRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $proposal_id
 * @property integer $region_id
 * @property Proposal $Proposal
 * @property Region $Region
 * 
 * @method integer           getId()          Returns the current record's "id" value
 * @method integer           getProposalId()  Returns the current record's "proposal_id" value
 * @method integer           getRegionId()    Returns the current record's "region_id" value
 * @method Proposal          getProposal()    Returns the current record's "Proposal" value
 * @method Region            getRegion()      Returns the current record's "Region" value
 * @method ProposalHasRegion setId()          Sets the current record's "id" value
 * @method ProposalHasRegion setProposalId()  Sets the current record's "proposal_id" value
 * @method ProposalHasRegion setRegionId()    Sets the current record's "region_id" value
 * @method ProposalHasRegion setProposal()    Sets the current record's "Proposal" value
 * @method ProposalHasRegion setRegion()      Sets the current record's "Region" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProposalHasRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proposal_has_region');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('proposal_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proposal', array(
             'local' => 'proposal_id',
             'foreign' => 'id'));

        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}