<?php

/**
 * BaseResponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $body
 * @property integer $initiative_id
 * @property Content $Content
 * 
 * @method integer  getId()            Returns the current record's "id" value
 * @method clob     getBody()          Returns the current record's "body" value
 * @method integer  getInitiativeId()  Returns the current record's "initiative_id" value
 * @method Content  getContent()       Returns the current record's "Content" value
 * @method Response setId()            Sets the current record's "id" value
 * @method Response setBody()          Sets the current record's "body" value
 * @method Response setInitiativeId()  Sets the current record's "initiative_id" value
 * @method Response setContent()       Sets the current record's "Content" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseResponse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('response');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('initiative_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'initiative_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}