<?php

/**
 * BaseGovermentNew
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * 
 * @method integer      getId() Returns the current record's "id" value
 * @method GovermentNew setId() Sets the current record's "id" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGovermentNew extends Content
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('goverment_new');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}