<?php

/**
 * BaseActionHasCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $action_id
 * @property Category $Category
 * 
 * @method integer           getCategoryId()  Returns the current record's "category_id" value
 * @method integer           getActionId()    Returns the current record's "action_id" value
 * @method Category          getCategory()    Returns the current record's "Category" value
 * @method ActionHasCategory setCategoryId()  Sets the current record's "category_id" value
 * @method ActionHasCategory setActionId()    Sets the current record's "action_id" value
 * @method ActionHasCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseActionHasCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('action_has_category');
        $this->hasColumn('category_id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('action_id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}