<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $nickname
 * @property integer $gender
 * @property string $telephone
 * @property string $address
 * @property string $postal_code
 * @property string $location
 * @property string $province
 * @property string $country
 * @property string $web
 * @property clob $about
 * @property boolean $subscription_email
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Regions
 * @property Doctrine_Collection $SubscriptionCategory
 * @property Doctrine_Collection $SubscriptionRegion
 * 
 * @method integer             getUserId()               Returns the current record's "user_id" value
 * @method string              getNickname()             Returns the current record's "nickname" value
 * @method integer             getGender()               Returns the current record's "gender" value
 * @method string              getTelephone()            Returns the current record's "telephone" value
 * @method string              getAddress()              Returns the current record's "address" value
 * @method string              getPostalCode()           Returns the current record's "postal_code" value
 * @method string              getLocation()             Returns the current record's "location" value
 * @method string              getProvince()             Returns the current record's "province" value
 * @method string              getCountry()              Returns the current record's "country" value
 * @method string              getWeb()                  Returns the current record's "web" value
 * @method clob                getAbout()                Returns the current record's "about" value
 * @method boolean             getSubscriptionEmail()    Returns the current record's "subscription_email" value
 * @method sfGuardUser         getUser()                 Returns the current record's "User" value
 * @method Doctrine_Collection getCategories()           Returns the current record's "Categories" collection
 * @method Doctrine_Collection getRegions()              Returns the current record's "Regions" collection
 * @method Doctrine_Collection getSubscriptionCategory() Returns the current record's "SubscriptionCategory" collection
 * @method Doctrine_Collection getSubscriptionRegion()   Returns the current record's "SubscriptionRegion" collection
 * @method sfGuardUserProfile  setUserId()               Sets the current record's "user_id" value
 * @method sfGuardUserProfile  setNickname()             Sets the current record's "nickname" value
 * @method sfGuardUserProfile  setGender()               Sets the current record's "gender" value
 * @method sfGuardUserProfile  setTelephone()            Sets the current record's "telephone" value
 * @method sfGuardUserProfile  setAddress()              Sets the current record's "address" value
 * @method sfGuardUserProfile  setPostalCode()           Sets the current record's "postal_code" value
 * @method sfGuardUserProfile  setLocation()             Sets the current record's "location" value
 * @method sfGuardUserProfile  setProvince()             Sets the current record's "province" value
 * @method sfGuardUserProfile  setCountry()              Sets the current record's "country" value
 * @method sfGuardUserProfile  setWeb()                  Sets the current record's "web" value
 * @method sfGuardUserProfile  setAbout()                Sets the current record's "about" value
 * @method sfGuardUserProfile  setSubscriptionEmail()    Sets the current record's "subscription_email" value
 * @method sfGuardUserProfile  setUser()                 Sets the current record's "User" value
 * @method sfGuardUserProfile  setCategories()           Sets the current record's "Categories" collection
 * @method sfGuardUserProfile  setRegions()              Sets the current record's "Regions" collection
 * @method sfGuardUserProfile  setSubscriptionCategory() Sets the current record's "SubscriptionCategory" collection
 * @method sfGuardUserProfile  setSubscriptionRegion()   Sets the current record's "SubscriptionRegion" collection
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('nickname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gender', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('telephone', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('postal_code', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('location', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('province', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('country', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('web', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('about', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('subscription_email', 'boolean', null, array(
             'default' => 0,
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Category as Categories', array(
             'refClass' => 'SubscriptionCategory',
             'local' => 'user_id',
             'foreign' => 'category_id'));

        $this->hasMany('Region as Regions', array(
             'refClass' => 'SubscriptionRegion',
             'local' => 'user_id',
             'foreign' => 'region_id'));

        $this->hasMany('SubscriptionCategory', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('SubscriptionRegion', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $geographical0 = new Doctrine_Template_Geographical();
        $this->actAs($timestampable0);
        $this->actAs($geographical0);
    }
}