<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $profiles
 * @property Doctrine_Collection $Proposals
 * @property Doctrine_Collection $Actions
 * @property Doctrine_Collection $ProposalHasCategory
 * @property Doctrine_Collection $SubscriptionCategory
 * @property Doctrine_Collection $ActionHasCategory
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method Doctrine_Collection getProfiles()             Returns the current record's "profiles" collection
 * @method Doctrine_Collection getProposals()            Returns the current record's "Proposals" collection
 * @method Doctrine_Collection getActions()              Returns the current record's "Actions" collection
 * @method Doctrine_Collection getProposalHasCategory()  Returns the current record's "ProposalHasCategory" collection
 * @method Doctrine_Collection getSubscriptionCategory() Returns the current record's "SubscriptionCategory" collection
 * @method Doctrine_Collection getActionHasCategory()    Returns the current record's "ActionHasCategory" collection
 * @method Category            setId()                   Sets the current record's "id" value
 * @method Category            setName()                 Sets the current record's "name" value
 * @method Category            setDescription()          Sets the current record's "description" value
 * @method Category            setProfiles()             Sets the current record's "profiles" collection
 * @method Category            setProposals()            Sets the current record's "Proposals" collection
 * @method Category            setActions()              Sets the current record's "Actions" collection
 * @method Category            setProposalHasCategory()  Sets the current record's "ProposalHasCategory" collection
 * @method Category            setSubscriptionCategory() Sets the current record's "SubscriptionCategory" collection
 * @method Category            setActionHasCategory()    Sets the current record's "ActionHasCategory" collection
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SfGuardUserProfile as profiles', array(
             'refClass' => 'SubscriptionCategory',
             'local' => 'category_id',
             'foreign' => 'user_profile_id'));

        $this->hasMany('Proposal as Proposals', array(
             'refClass' => 'ProposalHasCategory',
             'local' => 'category_id',
             'foreign' => 'proposal_id'));

        $this->hasMany('Action as Actions', array(
             'refClass' => 'ActionHasCategory',
             'local' => 'category_id',
             'foreign' => 'action_id'));

        $this->hasMany('ProposalHasCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('SubscriptionCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('ActionHasCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}