<?php

/**
 * BaseWorkshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $price
 * 
 * @method integer  getId()    Returns the current record's "id" value
 * @method decimal  getPrice() Returns the current record's "price" value
 * @method Workshop setId()    Sets the current record's "id" value
 * @method Workshop setPrice() Sets the current record's "price" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkshop extends Action
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('workshop');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'default' => 0,
             'type' => 'decimal',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}