<?php

/**
 * BaseVirtualMeetingAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $answer
 * @property integer $opinion_id
 * @property integer $user_id
 * @property Opinion $Opinion
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer              getId()          Returns the current record's "id" value
 * @method clob                 getAnswer()      Returns the current record's "answer" value
 * @method integer              getOpinionId()   Returns the current record's "opinion_id" value
 * @method integer              getUserId()      Returns the current record's "user_id" value
 * @method Opinion              getOpinion()     Returns the current record's "Opinion" value
 * @method sfGuardUser          getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method VirtualMeetingAnswer setId()          Sets the current record's "id" value
 * @method VirtualMeetingAnswer setAnswer()      Sets the current record's "answer" value
 * @method VirtualMeetingAnswer setOpinionId()   Sets the current record's "opinion_id" value
 * @method VirtualMeetingAnswer setUserId()      Sets the current record's "user_id" value
 * @method VirtualMeetingAnswer setOpinion()     Sets the current record's "Opinion" value
 * @method VirtualMeetingAnswer setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVirtualMeetingAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('virtual_meeting_answer');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('answer', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('opinion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Opinion', array(
             'local' => 'opinion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}