<?php

/**
 * BaseActionUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $action_id
 * @property integer $action_user_id
 * @property Action $Action
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getActionId()       Returns the current record's "action_id" value
 * @method integer     getActionUserId()   Returns the current record's "action_user_id" value
 * @method Action      getAction()         Returns the current record's "Action" value
 * @method sfGuardUser getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method ActionUser  setActionId()       Sets the current record's "action_id" value
 * @method ActionUser  setActionUserId()   Sets the current record's "action_user_id" value
 * @method ActionUser  setAction()         Sets the current record's "Action" value
 * @method ActionUser  setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseActionUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('action_user');
        $this->hasColumn('action_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('action_user_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Action', array(
             'local' => 'action_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'action_user_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}