<?php

/**
 * BaseResponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $body
 * @property integer $content_id
 * @property string $content_type
 * 
 * @method integer  getId()           Returns the current record's "id" value
 * @method clob     getBody()         Returns the current record's "body" value
 * @method integer  getContentId()    Returns the current record's "content_id" value
 * @method string   getContentType()  Returns the current record's "content_type" value
 * @method Response setId()           Sets the current record's "id" value
 * @method Response setBody()         Sets the current record's "body" value
 * @method Response setContentId()    Sets the current record's "content_id" value
 * @method Response setContentType()  Sets the current record's "content_type" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResponse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('response');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content_type', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));


        $this->index('IX_Response_1', array(
             'fields' => 
             array(
              0 => 'content_id',
              1 => 'content_type',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}