<?php

/**
 * BaseGovermentConsultation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $start_date
 * @property date $end_date
 * @property integer $opinion_possibility_group_id
 * @property OpinionPossibilityGroup $OpinionPossibilityGroup
 * 
 * @method integer                 getId()                           Returns the current record's "id" value
 * @method date                    getStartDate()                    Returns the current record's "start_date" value
 * @method date                    getEndDate()                      Returns the current record's "end_date" value
 * @method integer                 getOpinionPossibilityGroupId()    Returns the current record's "opinion_possibility_group_id" value
 * @method OpinionPossibilityGroup getOpinionPossibilityGroup()      Returns the current record's "OpinionPossibilityGroup" value
 * @method GovermentConsultation   setId()                           Sets the current record's "id" value
 * @method GovermentConsultation   setStartDate()                    Sets the current record's "start_date" value
 * @method GovermentConsultation   setEndDate()                      Sets the current record's "end_date" value
 * @method GovermentConsultation   setOpinionPossibilityGroupId()    Sets the current record's "opinion_possibility_group_id" value
 * @method GovermentConsultation   setOpinionPossibilityGroup()      Sets the current record's "OpinionPossibilityGroup" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGovermentConsultation extends Proposal
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('goverment_consultation');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('opinion_possibility_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OpinionPossibilityGroup', array(
             'local' => 'opinion_possibility_group_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}