<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Profiles
 * @property Doctrine_Collection $Proposals
 * @property Doctrine_Collection $ContentHasRegion
 * @property Doctrine_Collection $SubscriptionRegion
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method Doctrine_Collection getProfiles()           Returns the current record's "Profiles" collection
 * @method Doctrine_Collection getProposals()          Returns the current record's "Proposals" collection
 * @method Doctrine_Collection getContentHasRegion()   Returns the current record's "ContentHasRegion" collection
 * @method Doctrine_Collection getSubscriptionRegion() Returns the current record's "SubscriptionRegion" collection
 * @method Region              setId()                 Sets the current record's "id" value
 * @method Region              setName()               Sets the current record's "name" value
 * @method Region              setDescription()        Sets the current record's "description" value
 * @method Region              setProfiles()           Sets the current record's "Profiles" collection
 * @method Region              setProposals()          Sets the current record's "Proposals" collection
 * @method Region              setContentHasRegion()   Sets the current record's "ContentHasRegion" collection
 * @method Region              setSubscriptionRegion() Sets the current record's "SubscriptionRegion" collection
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserProfile as Profiles', array(
             'refClass' => 'SubscriptionRegion',
             'local' => 'region_id',
             'foreign' => 'user_id'));

        $this->hasMany('Content as Proposals', array(
             'refClass' => 'ContentHasRegion',
             'local' => 'region_id',
             'foreign' => 'content_id'));

        $this->hasMany('ContentHasRegion', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $this->hasMany('SubscriptionRegion', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($nestedset0);
    }
}