<?php

/**
 * BaseVirtualMeeting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property clob $body
 * @property integer $user_id
 * @property date $answers_start_date
 * @property date $answers_end_date
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer        getId()                 Returns the current record's "id" value
 * @method string         getTitle()              Returns the current record's "title" value
 * @method clob           getBody()               Returns the current record's "body" value
 * @method integer        getUserId()             Returns the current record's "user_id" value
 * @method date           getAnswersStartDate()   Returns the current record's "answers_start_date" value
 * @method date           getAnswersEndDate()     Returns the current record's "answers_end_date" value
 * @method sfGuardUser    getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method VirtualMeeting setId()                 Sets the current record's "id" value
 * @method VirtualMeeting setTitle()              Sets the current record's "title" value
 * @method VirtualMeeting setBody()               Sets the current record's "body" value
 * @method VirtualMeeting setUserId()             Sets the current record's "user_id" value
 * @method VirtualMeeting setAnswersStartDate()   Sets the current record's "answers_start_date" value
 * @method VirtualMeeting setAnswersEndDate()     Sets the current record's "answers_end_date" value
 * @method VirtualMeeting setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseVirtualMeeting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('virtual_meeting');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('answers_start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('answers_end_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}