<?php

/**
 * BaseAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $author
 * @property date $action_date
 * @property string $location
 * @property integer $min_users_allowed
 * @property integer $max_users_allowed
 * @property date $register_start_date
 * @property date $register_end_date
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $ActionHasUser
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getAuthor()              Returns the current record's "author" value
 * @method date                getActionDate()          Returns the current record's "action_date" value
 * @method string              getLocation()            Returns the current record's "location" value
 * @method integer             getMinUsersAllowed()     Returns the current record's "min_users_allowed" value
 * @method integer             getMaxUsersAllowed()     Returns the current record's "max_users_allowed" value
 * @method date                getRegisterStartDate()   Returns the current record's "register_start_date" value
 * @method date                getRegisterEndDate()     Returns the current record's "register_end_date" value
 * @method Doctrine_Collection getUsers()               Returns the current record's "Users" collection
 * @method Doctrine_Collection getActionHasUser()       Returns the current record's "ActionHasUser" collection
 * @method Action              setId()                  Sets the current record's "id" value
 * @method Action              setAuthor()              Sets the current record's "author" value
 * @method Action              setActionDate()          Sets the current record's "action_date" value
 * @method Action              setLocation()            Sets the current record's "location" value
 * @method Action              setMinUsersAllowed()     Sets the current record's "min_users_allowed" value
 * @method Action              setMaxUsersAllowed()     Sets the current record's "max_users_allowed" value
 * @method Action              setRegisterStartDate()   Sets the current record's "register_start_date" value
 * @method Action              setRegisterEndDate()     Sets the current record's "register_end_date" value
 * @method Action              setUsers()               Sets the current record's "Users" collection
 * @method Action              setActionHasUser()       Sets the current record's "ActionHasUser" collection
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAction extends Content
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('action');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('author', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('action_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('min_users_allowed', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('max_users_allowed', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('register_start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('register_end_date', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'ActionHasUser',
             'local' => 'action_id',
             'foreign' => 'user_id'));

        $this->hasMany('ActionHasUser', array(
             'local' => 'id',
             'foreign' => 'action_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}