# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sfImageTransformPlugin:
    default_adapter: GD
    mime_type:
      auto_detect: true
      library: gd_mime_type
  sf_guard_plugin:
    remember_key_expiration_age:  2592000   # 30 days in seconds
    remember_cookie_name:         demofonyAdminRememberMe
  sf_admin_theme_jroller_plugin:
    # icons for each buttons
    # icon class as: ui-icon-value
    icons:
      new: plus
      filter: check
      filters: search
      reset: circle-close
      show: document
      edit: pencil
      delete: trash
      list: arrowreturnthick-1-w
      save: circle-check
      saveAndAdd: circle-plus
      first: seek-first
      previous: seek-prev
      next: seek-next
      last: seek-end
  sfDoctrineJCroppablePlugin:
    models:
      Content:
        directory:    images/content
        images:
          image:
            ratio:      1.5
            sizes:
              thumb:    { width: 160 }
              main:     { width: 210 }
      SfGuardUserProfile:
        directory:    images/user
        images:
          image:
            ratio:      1
            sizes:
              thumb:    { width: 50, height: 40 }
              main:     { width: 120, height: 115 }