name:     Admin menu
attributes: {id: admin_menu, class: sf-menu}
children:
  site_content:
    label:         Content
    requires_auth: true
    route:   ''
    attributes: {class: ui-corner-left}
    children:
      manage_goverment_news:
        label:   Goverment news
        route:   @goverment_new
        credentials: [Permission_admin]
      manage_goverment_proposals:
        label:   Goverment proposals
        route:   @goverment_proposal
        credentials: [Permission_admin]
      manage_goverment_consultations:
        label:   Goverment consultations
        route:   @goverment_consultation
        credentials: [Permission_admin]
      manage_goverment_news:
        label:   Goverment news
        route:   @goverment_new
        credentials: [Permission_admin]
      manage_workshops:
        label:   Workshops
        route:   @workshop
        credentials: [Permission_admin]
      manage_citizen_proposals:
        label:   Citizen proposals
        route:   @citizen_proposal
        credentials: [Permission_admin]
      manage_citizen_actions:
        label:   Citizen actions
        route:   @citizen_action
        credentials: [Permission_admin]
      manage_virtual_meeting:
        label:   Virtual meetings
        route:   @virtual_meeting
        credentials: [Permission_admin]
  comments_opionions:
    label:          Comments and opinions
    requires_auth: true
    route:   ''
    children:
      manage_comments:
        label:   Manage comments
        route:   commentAdmin/index
        credentials: [Permission_admin]
      manage_comments_reports:
        label:   Manage comments reports
        route:   commentReportAdmin/index
        credentials: [Permission_admin]
  site_admin:
    label:          Site admin
    requires_auth: true
    route:   ''
    children:
      manage_regions:
        label:   Manage regions
        route:   region/nested
        credentials: [Permission_admin]
      manage_categories:
        label:   Manage categories
        route:   @category
        credentials: [Permission_admin]
  user_admin:
    label:          User Admin
    requires_auth: true
    route:   @sf_guard_user
    children:
      manage_users:
        label:   Manage users
        route:   @sf_guard_user
        credentials: [Permission_admin]
      manage_groups:
        label:   Manage groups
        route:   @sf_guard_permission
        credentials: [Permission_admin]
      manage_permissions:
        label:   Manage permissions
        route:   @sf_guard_permission
        credentials: [Permission_admin]
  signout:
    label:   Sign out
    route:   @sf_guard_signout
    requires_auth: true
    attributes: {class: ui-corner-right}