name:     Admin menu
attributes: {id: admin_menu, class: sf-menu}
children:
  site_content:
    label:         Content
    requires_auth: true
    route:   ''
    children:
      manage_citizen_proposals:
        label:   Citizen proposal
        route:   @citizen_proposal
        credentials: [Permission_admin]
  site_admin:
    label:          Site admin
    requires_auth: true
    route:   ''
    children:
      manage_regions:
        label:   Manage regions
        route:   @region
        credentials: [Permission_admin]
      manage_categories:
        label:   Manage categories
        route:   @category
        credentials: [Permission_admin]
  user_admin:
    label:          User Admin
    requires_auth: true
    route:   @sf_guard_user
    children:
      manage_users:
        label:   Manage users
        route:   @sf_guard_user
        credentials: [Permission_admin]
      manage_groups:
        label:   Manage groups
        route:   @sf_guard_permission
        credentials: [Permission_admin]
      manage_permissions:
        label:   Manage permissions
        route:   @sf_guard_permission
        credentials: [Permission_admin]
  signin:
    label:   Sign in
    route:   @sf_guard_signin
    requires_no_auth: true
    attributes: {class: signin}
  signout:
    label:   Sign out
    route:   @sf_guard_signout
    requires_auth: true