# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /blueprint/blueprint/screen.css: { media: 'screen,projection' }
    - /blueprint/blueprint/print.css: { media: print }
    - /jquery/ui/css/pepper-grinder/jquery-ui-1.8.11.custom.css
    - main.css
    - /css/admin_menu.css
    - /jquery/superfish/css/superfish.css
    - /blueprint/blueprint/ie.css { condition: IE 8 }
    

  javascripts:    [/jquery/jquery-1.5.1.min.js, /jquery/ui/jquery-ui-1.8.11.custom.min.js, /jquery/superfish/js/hoverIntent.js, /jquery/superfish/js/jquery.bgiframe.min.js, /jquery/superfish/js/superfish.js]

  has_layout:     true
  layout:         layout
