generator:
  class: sfDoctrineGenerator
  param:
    model_class:           VirtualMeeting
    theme:                 jroller2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          virtual_meeting
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title,sfGuardUser,answers_start_date,answers_end_date]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
