<?php

/**
 * BaseOpinionPossibilityGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $can_text_be_added
 * @property Doctrine_Collection $OpinionPossibility
 * 
 * @method integer                 getId()                 Returns the current record's "id" value
 * @method string                  getName()               Returns the current record's "name" value
 * @method boolean                 getCanTextBeAdded()     Returns the current record's "can_text_be_added" value
 * @method Doctrine_Collection     getOpinionPossibility() Returns the current record's "OpinionPossibility" collection
 * @method OpinionPossibilityGroup setId()                 Sets the current record's "id" value
 * @method OpinionPossibilityGroup setName()               Sets the current record's "name" value
 * @method OpinionPossibilityGroup setCanTextBeAdded()     Sets the current record's "can_text_be_added" value
 * @method OpinionPossibilityGroup setOpinionPossibility() Sets the current record's "OpinionPossibility" collection
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpinionPossibilityGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('opinion_possibility_group');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('can_text_be_added', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OpinionPossibility', array(
             'local' => 'id',
             'foreign' => 'opinion_possibility_group_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}