<?php

/**
 * BaseCommentReport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $reason
 * @property string $referer
 * @property enum $state
 * @property integer $id_comment
 * @property Comment $Comment
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method clob          getReason()     Returns the current record's "reason" value
 * @method string        getReferer()    Returns the current record's "referer" value
 * @method enum          getState()      Returns the current record's "state" value
 * @method integer       getIdComment()  Returns the current record's "id_comment" value
 * @method Comment       getComment()    Returns the current record's "Comment" value
 * @method CommentReport setId()         Sets the current record's "id" value
 * @method CommentReport setReason()     Sets the current record's "reason" value
 * @method CommentReport setReferer()    Sets the current record's "referer" value
 * @method CommentReport setState()      Sets the current record's "state" value
 * @method CommentReport setIdComment()  Sets the current record's "id_comment" value
 * @method CommentReport setComment()    Sets the current record's "Comment" value
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCommentReport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment_report');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('reason', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('referer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('state', 'enum', null, array(
             'default' => 'untreated',
             'type' => 'enum',
             'values' => 
             array(
              0 => 'valid',
              1 => 'invalid',
              2 => 'untreated',
             ),
             ));
        $this->hasColumn('id_comment', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comment', array(
             'local' => 'id_comment',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}