<?php

/**
 * Action
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Action extends BaseAction
{
  
  public function isOpened() {
    if (strtotime($this->getActionDate()) >= time() && (!$this->getMaxUsersAllowed() || ($this->getMaxUsersAllowed() < $this->getNumberUsersRegistered()))) {
      return true;
    }
    else return false;
  }
  
  public function getNumberUsersRegistered() {
    $q = $this->getUserRegisteredQuery();
    return $q->execute()->count();
  }
  
  public function registerUser($user) {
    $actionUser = new ActionHasUser();
    $actionUser->setUserId($user->getId());
    $actionUser->setType(get_class($this));
    $actionUser->setActionId($this->getId());
    $actionUser->save();
  }
  
  public function unregisterUser($user) {
    $query= $this->getUserRegisteredQuery();
    $query->andWhere('ur.user_id = ?',$user->getId());
    $actionUser = $query->execute()->getFirst();
    $actionUser->delete();
  }
  
  protected function getUserRegisteredQuery() {
    return Doctrine_Core::getTable('ActionHasUser')->createQuery('ur')->where('ur.action_id = ? ',$this->getId())->andWhere('ur.type = ?',get_class($this));
  }
}
