<?php

/**
 * ActionHasUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionHasUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionHasUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionHasUser');
    }
}