<?php

/**
 * ActionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionTable extends ContentTable
{
    protected $inheritedClasses = array('CitizenAction','Workshop');
    protected $select = 'id, created_at, views, action_date, active,latitude, longitude';
    
    /**
     * Returns an instance of this class.
     *
     * @return object ActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Action');
    }
}