<?php

/**
 * CitizenActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitizenActionTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CitizenActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CitizenAction');
    }
}