<?php

/**
 * CitizenAction
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class CitizenAction extends BaseCitizenAction
{
  public function getColor() {
    return 'yellow';
  }
  
  public function getGmapIcon() {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url'));

    return public_path('images/icons/pin_yellow.png');
  }
}
