<?php

/**
 * CitizenProposalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitizenProposalTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CitizenProposalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CitizenProposal');
    }
}