<?php

/**
 * CitizenProposal
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class CitizenProposal extends BaseCitizenProposal
{
  public function getLetter() {
    return 'c';
  }
  public function getSymbol() {
    return $this->getLetter();
  }
}
