<?php

/**
 * ContentHasCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentHasCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentHasCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentHasCategory');
    }
}