<?php

/**
 * ContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Content');
    }
}