<?php

/**
 * ContentHasRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentHasRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentHasRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentHasRegion');
    }
}