<?php

/**
 * GovermentProposalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GovermentProposalTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GovermentProposalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GovermentProposal');
    }
}