<?php

/**
 * GovermentNewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GovermentNewTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GovermentNewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GovermentNew');
    }
}