<?php

/**
 * GovermentConsultationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GovermentConsultationTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GovermentConsultationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GovermentConsultation');
    }
}