<?php

/**
 * ProposalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProposalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProposalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proposal');
    }
}