<?php

/**
 * ProposalTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProposalTable extends ContentTable
{
  public $inheritedClasses = array('CitizenProposal','GovermentProposal','GovermentConsultation');
    /**
     * Returns an instance of this class.
     *
     * @return object ProposalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proposal');
    }
    
    
  public function getActiveCombined($limit = null)
  {
    $results = array();
    $q = Doctrine_Core::getTable('CitizenProposal')->createQuery('c')->where('c.active = 1')->addOrderBy('c.created_at desc');
    if ($limit) {
      $q->limit($limit);
    }
    $array1 = $q->execute()->getData();
    
    $q = Doctrine_Core::getTable('GovermentProposal')->createQuery('c')->where('c.active = 1')->addOrderBy('c.created_at desc');
    if ($limit) {
      $q->limit($limit);
    }
    $array2 = $q->execute()->getData();
    
    $q = Doctrine_Core::getTable('GovermentConsultation')->createQuery('c')->where('c.active = 1')->addOrderBy('c.created_at desc');
    if ($limit) {
      $q->limit($limit);
    }
    $array3 = $q->execute()->getData();
    
    $results = array_merge($array1,$array2,$array3);
    // var_dump($results);
    usort($results, array('ProposalTable', 'cmp_obj'));
    if ($limit) {
      $results = array_slice($results, 0, $limit);
    }
    return $results;
  }
  
  
  static function cmp_obj($a, $b)
  {
    $atime = strtotime($a->getCreatedAt());
    $btime = strtotime($b->getCreatedAt());
    
    if ($atime == $btime) {
        return 0;
    }
    return ($atime > $btime) ? +1 : -1;
  }
  
}