<?php

/**
 * ProposalHasCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProposalHasCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProposalHasCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProposalHasCategory');
    }
}