<?php

/**
 * ProposalHasRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProposalHasRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProposalHasRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProposalHasRegion');
    }
}