<?php

/**
 * ResponseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Response');
    }
}