<?php

/**
 * SfGuardUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserProfile');
    }
}