<?php

/**
 * sfGuardUserProfile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
  public function getImageSrcWithDefault($fieldName, $size = 'thumb') {
    if (!$this->getImage() && $size = 'thumb') {
      $relative_url = sfContext::getInstance()->getRequest()->getRelativeUrlRoot();
      return $relative_url.'/'.$this->getImageDirWeb().'/default_avatar.gif';
    }
    else return $this->getImageSrc($fieldName,$size);
  }
  
}
