<?php

/**
 * sfGuardUserProfile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
  public function getImageSrcWithDefault($fieldName, $size = 'thumb') {
    if (!$this->getImage()) {
      $relative_url = sfContext::getInstance()->getRequest()->getRelativeUrlRoot();
      return $relative_url.'/images/no-profile-'.$size.'.gif';
    }
    else return $this->getImageSrc($fieldName,$size);
  }
  
  public function getGmap() {
    if ($this->getLatitude() && $this->getLongitude()) {
      return GMap::loadMap('100%',200,array($this));
    }
    else return null;
  }
  
  public function getGmapHtml() {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('I18N'));
    return $this->getUser()->__toString().' '.__('lives here');
  }
  
  public function getGmapIcon() {
    return null;
  }
}
