<?php

/**
 * SubscriptionRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubscriptionRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubscriptionRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubscriptionRegion');
    }
}