<?php

/**
 * SubscriptionCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubscriptionCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubscriptionCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubscriptionCategory');
    }
}