<?php

/**
 * VirtualMeetingQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualMeetingQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualMeetingQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualMeetingQuestion');
    }
}