<?php

/**
 * VirtualMeetingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualMeetingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualMeetingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualMeeting');
    }
}