<?php

/**
 * VirtualMeetingTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualMeetingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualMeetingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualMeeting');
    }
    
    public function getActiveQuery($limit = null)
    {
      $q = self::createQuery('vm')
      ->where('vm.active = 1')
      ->addOrderBy('vm.answers_end_date desc');
      
      if ($limit) {
        $q->limit($limit);
      }
   
      return $q;
    }
    
    public function getActiveAndNotArchivedQuery($limit = null)
    {
      $q = $this->getActiveQuery();
      $q->andWhere('vm.archived = 0');
      
      if ($limit) {
        $q->limit($limit);
      }
   
      return $q;
    }
    
    public function getActiveAndArchivedQuery($limit = null)
    {
      $q = $this->getActiveQuery();
      $q->andWhere('vm.archived = 1');
      
      if ($limit) {
        $q->limit($limit);
      }
   
      return $q;
    }
    
}