<?php

/**
 * VirtualMeetingQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VirtualMeetingQuestion extends BaseVirtualMeetingQuestion
{
}
