<?php

/**
 * VirtualMeetingAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualMeetingAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualMeetingAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualMeetingAnswer');
    }
}