<?php

/**
 * WorkshopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkshopTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkshopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Workshop');
    }
}