# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  mail:
    admin: marc@teclliure.net
  cultures:
    enabled:
      en: English
      es: Español
      ca: Català
  sf_guard_plugin:
    signin_form: sfGuardFormSigninFrontend
    remember_key_expiration_age:  2592000   # 30 days in seconds
    remember_cookie_name:         demofonyFrontRememberMe
  sfDoctrineJCroppablePlugin:
    models:
      Content:
        directory:    images/content
        images:
          image:
            ratio:      1.5
            sizes:
              thumb:    { width: 50, height: 45 }
              main:     { width: 210, height: 140 }
      SfGuardUserProfile:
        directory:    images/user
        images:
          image:
            ratio:      1
            sizes:
              thumb:    { width: 50, height: 40 }
              main:     { width: 120, height: 115 }
            preview:   thumb
  sfImageTransformPlugin:
    default_adapter: GD
    mime_type:
      auto_detect: true
      library: gd_mime_type
  vjCommentPlugin:
    #false by default
    pagination_active: true
    #10 by default
    max_per_page: 5
    restricted: true
  purifier:
    #set to false use only your allowed tags
    merge: false
    #by default, [blockquote,strong,div,br] are allowed
    #set to [i,u] with merge to true allows [blockquote,strong,div,br,i,u]
    #set to [] with merge to false disables allowed tags
    allowed_tags: [i,u, a, blockquote, strong]
  
