# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Demofony
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - /blueprint/blueprint/screen.css: { media: 'screen,projection' }
    - /blueprint/blueprint/print.css: { media: print }
    - /blueprint/blueprint/ie.css { condition: IE 8 }
    - /jquery/ui/css/pepper-grinder/jquery-ui-1.8.11.custom.css
    - main.css
    

  javascripts:
    - /jquery/jquery-1.5.1.min.js
    - /jquery/ui/jquery-ui-1.8.11.custom.min.js
    - frontend.js

  has_layout:     true
  layout:         layout
