<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    demofony
 * @subpackage model
 * @author     Marc Montañés <marc@teclliure.net>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function getNumberOpinions() {
    $num = Doctrine_core::getTable('Opinion')->createQuery('o')->where('o.user_id = ?',$this->getId())->execute()->count();
    $num2 = Doctrine_core::getTable('OpinionLike')->createQuery('ol')->where('ol.user_id = ?',$this->getId())->execute()->count();
    return $num+$num2;
  }
  
  public function getOpinions() {
    return Doctrine_core::getTable('Opinion')->createQuery('o')->leftJoin('o.OpinionLike ol')->where('o.user_id = ?',$this->getId())->andWhere('o.innapropiate = 0')->orWhere('ol.user_id = ?',$this->getId())->execute();
  }
  
  public function getNumberComments() {
    return Doctrine_core::getTable('Comment')->createQuery('c')->where('c.user_id = ?',$this->getId())->execute()->count();
  }
  
  public function getNumberInitiatives() {
    return Doctrine_core::getTable('CitizenProposal')->createQuery('cp')->where('cp.user_id = ?',$this->getId())->execute()->count();
  }

  public function getInitiatives() {
    return Doctrine_core::getTable('CitizenProposal')->createQuery('cp')->where('cp.user_id = ?',$this->getId())->andWhere('cp.active = 1')->execute();
  }
  
  public function getActions() {
    return Doctrine::getTable('Action')->getObjectsUnion('ORDER BY action_date desc', null, null, null, $where = 'active = 1 AND user_id='.$this->getId());
  }
  
  public function getNumberActions() {
    return count($this->getActions());
  }
}
