generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Comment
    theme:                 jroller2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          commentAdmin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_delete:          { label: Disable }
        record_model:       { label: Model }
        record_id:          { label: Record }
        created_at:         { label: Posted the }
        edition_reason:     { label: Reason }
      list:
        title:              Comments list
        display:            [author, _body, is_delete, created_at]
        sort:               [created_at, desc]
        actions:            {}
        table_method:       getAdminQuery
        object_actions:
          _edit:            { label: Edit }
          _delete:          { label: Disable }
          restore:          { label: Restore }
          reply:            { label: Reply }
        batch_actions:
          _delete: ~
          restore:          { label: Restore }
      filter:
        display:            [id, is_delete, record_model, user_id, author_name, author_email, author_website, body, created_at]
      form:
        display:
          Author:           [author_name, author_email, author_website, user_name]
          Body:             [body]
          Edition:          [edition_reason]
        class:              commentAdminForm
      edit:
        title:              Edit comment
        actions:
          _list:            { label: Back to list }
          _delete:          { label: Delete }
          restore:          { label: Restore, action: restore }
          save_and_delete:  { label: Save and Delete }
          save_and_restore: { label: Save and Restore }
          _save:            { label: Save }
      new:
        title:              Reply to comment
        display:
          Author:           [author_name, author_email, author_website]
          Body:             [reply_author, body, _bodyReply]
