<?php

/**
 * PluginOpinionLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpinionLikeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOpinionLikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOpinionLike');
    }
}