<?php

/**
 * PluginOpinion
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class PluginOpinion extends BaseOpinion
{
  public function __toString() {
    if ($this->getOpinionPossibilityId()) {
      return $this->getOpinionPossibility()->getName();
    }
    else {
      return $this->getOpinion();
    }
  }
  
  public function countOpinionsLike() {
    $query = Doctrine::getTable('OpinionLike')->createQuery('o')->where('o.opinion_id = ?',$this->getId());
    return $query->count();
  }
  
  public function getObject() {
    return Doctrine::getTable($this->getObjectClass())->findOneBy('id',$this->getObjectId());
  }
  
  public function hasMarkedAsSpam($user) {
    $query = Doctrine::getTable('OpinionMarkedAsSpam')->createQuery('os')->where('os.opinion_id = ?',$this->getId())->andWhere('os.user_id = ?',$user->getId());
    return $query->count();
  }

}