<?php

/**
 * PluginOpinionMarkedAsSpamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpinionMarkedAsSpamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOpinionMarkedAsSpamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOpinionMarkedAsSpam');
    }
}