<?php

/**
 * PluginOpinionLike
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class PluginOpinionLike extends BaseOpinionLike
{
  
  public function __toString() {
    sfContext::getInstance()->getConfiguration()->loadHelpers('I18N');
    return $this->getOpinion().' '.__('like').' '.$this->getOpinion()->getSfGuardUser();
  }
}