<?php

/**
 * PluginOpinionPossibilityGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpinionPossibilityGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOpinionPossibilityGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOpinionPossibilityGroup');
    }
}