<?php

/**
 * PluginOpinionLike
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class PluginOpinionLike extends BaseOpinionLike
{
  
  public function __toString() {
    sfContext::getInstance()->getConfiguration()->loadHelpers('I18N');
    return $this->getOpinion().' '.__('like').' '.$this->getOpinion()->getSfGuardUser();
  }
  
  public function getGmapHtml() {
    SfContext::getInstance()->getConfiguration()->loadHelpers(array('Tag','I18N','Url'));
    return link_to($this->getSfGuardUser(),'user/showProfile?username='.$this->getSfGuardUser()->getUsername()).' '.__('opined like').' '.$this->getOpinion()->getSfGuardUser();
  }
  
  public function getGmapIcon() {
    if ($this->getOpinion()->getOpinionPossibility()) {
      if ($this->getOpinion()->getOpinionPossibility()->getGmapBubbleImage()) {
        SfContext::getInstance()->getConfiguration()->loadHelpers(array('Asset'));
        return image_path('gmap_icons/'.$this->getOpinion()->getOpinionPossibility()->getGmapBubbleImage());
      }
    }
    return null;
  }
}