<?php

/**
 * PluginOpinionPossibilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpinionPossibilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOpinionPossibilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOpinionPossibility');
    }
}