generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OpinionPossibility
    theme:                 jroller2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          opinion_possibility
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name,opinion_possibility_group]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
