<?php

/**
 * OpinionPossibilityGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpinionPossibilityGroupTable extends PluginOpinionPossibilityGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpinionPossibilityGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpinionPossibilityGroup');
    }
}