<?php

/**
 * OpinionPossibilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpinionPossibilityTable extends PluginOpinionPossibilityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpinionPossibilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpinionPossibility');
    }
}