<?php

/**
 * OpinionMarkedAsSpamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpinionMarkedAsSpamTable extends PluginOpinionMarkedAsSpamTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpinionMarkedAsSpamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpinionMarkedAsSpam');
    }
}