<?php

/**
 * OpinionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpinionTable extends PluginOpinionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpinionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Opinion');
    }
}