<?php

/**
 * OpinionLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpinionLikeTable extends PluginOpinionLikeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpinionLikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpinionLike');
    }
}