generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GovermentNew
    theme:                 jroller2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          goverment_new
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title, sfGuardUser, publish_date, created_at, updated_at, active]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
