generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GovermentProposal
    theme:                 jroller2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          goverment_proposal
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields:
        sfGuardUser: { label: Author }
      list:
        display: [=title, sfGuardUser, created_at, updated_at, active, views]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
