sfGuardUserProfile:
  actAs:
    Timestampable: 
    Geographical: 
    JCroppable:
      images: [image]
  columns:
    user_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    born_date:
      type: date
    gender:
      type: integer
    telephone:
      type: string(25)
    address:
      type: string(255)
    postal_code:
      type: string(10)
    location:
      type: string(150)
    province:
      type: string(150)
    country:
      type: string(150)
    web:
      type: string(255)
    about:
      type: clob
    subscription_email:
      default: 0
      type: boolean
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Profile
      onDelete: CASCADE
      type: one
      foreignType: one
      local: user_id
      foreign: id
    Categories:
      class: Category
      refClass: SubscriptionCategory
      local: user_id
      foreign: category_id
    Regions:
      class: Region
      refClass: SubscriptionRegion
      local: user_id
      foreign: region_id
Category:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    name:
      unique: true
      type: string(100)
      notnull: true
    description:
      type: string(255)
  relations:
    Profiles:
      class: sfGuardUserProfile
      refClass: SubscriptionCategory
      local: category_id
      foreign: user_id
    Contents:
      class: Content
      refClass: ContentHasCategory
      local: category_id
      foreign: content_id
Content:
  actAs:
    Timestampable: 
    Sluggable:
      alias: slug
      unique: true
      options: 
      fields: [type,title]
      uniqueBy: [title,type]
    Geographical: 
    JCroppable:
      images: [image]
    Commentable: 
  columns:
    id:
      primary: true
      unique: true
      type: integer
      notnull: true
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    body:
      type: clob
      notnull: true
    video:
      type: string(255)
    active:
      default: 1
      type: boolean
      notnull: true
    views:
      default: 0
      type: integer(16)
    type:
      type: string(255)
      notnull: true
    user_id:
      type: integer
      notnull: true
  relations:
    sfGuardUser:
      local: user_id
      foreign: id
    Categories:
      class: Category
      refClass: ContentHasCategory
      local: content_id
      foreign: category_id
    Users:
      class: sfGuardUser
      refClass: ActionHasUser
      local: action_id
      foreign: user_id
    Regions:
      class: Region
      refClass: ContentHasRegion
      local: content_id
      foreign: region_id
Region:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    name:
      unique: true
      type: string(100)
      notnull: true
    description:
      type: string(255)
  relations:
    Profiles:
      class: sfGuardUserProfile
      refClass: SubscriptionRegion
      local: region_id
      foreign: user_id
    Contents:
      class: Content
      refClass: ContentHasRegion
      local: region_id
      foreign: content_id
Response:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    body:
      type: clob
      notnull: true
    content_id:
      type: integer
  relations:
    Content:
      onDelete: CASCADE
      local: content_id
      foreign: id
VirtualMeeting:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    body:
      type: clob
      notnull: true
    user_id:
      type: integer
      notnull: true
    answers_start_date:
      type: date
      notnull: true
    answers_end_date:
      type: date
      notnull: true
  relations:
    sfGuardUser:
      onDelete: CASCADE
      local: user_id
      foreign: id
VirtualMeetingAnswer:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    answer:
      type: clob
      notnull: true
    opinion_id:
      type: integer
      notnull: true
    user_id:
      type: integer
      notnull: true
  relations:
    Opinion:
      onDelete: CASCADE
      local: opinion_id
      foreign: id
    sfGuardUser:
      onDelete: CASCADE
      local: user_id
      foreign: id
SubscriptionCategory:
  columns:
    user_id:
      primary: true
      type: integer
      notnull: true
    category_id:
      primary: true
      type: integer
      notnull: true
  indexes:
    IX_SubscriptionCategory_1:
      fields: [user_id, category_id]
      type: unique
  relations:
    sfGuardUserProfile:
      onDelete: CASCADE
      local: user_id
      foreign: user_id
    Category:
      onDelete: CASCADE
      local: category_id
      foreign: id
SubscriptionRegion:
  columns:
    user_id:
      primary: true
      type: integer
      notnull: true
    region_id:
      primary: true
      type: integer
      notnull: true
  indexes:
    IX_SubscriptionRegion_1:
      fields: [user_id, region_id]
      type: unique
  relations:
    sfGuardUserProfile:
      onDelete: CASCADE
      local: user_id
      foreign: user_id
    Region:
      onDelete: CASCADE
      local: region_id
      foreign: id
CitizenProposal:
  columns:
    tip:
      type: clob
  inheritance:
    extends: Content
    type: column_aggregation
    keyField: type
    keyValue: CitizenProposal
GovermentProposal:
  inheritance:
    extends: Content
    type: column_aggregation
    keyField: type
    keyValue: GovermentProposal
GovermentNew:
  inheritance:
    extends: Content
    type: column_aggregation
    keyField: type
    keyValue: GovermentNew
GovermentConsultation:
  columns:
    start_date:
      type: date
    end_date:
      type: date
  inheritance:
    extends: Content
    type: column_aggregation
    keyField: type
    keyValue: GovermentConsultation
Workshop:
  columns:
    author:
      type: string(150)
    action_date:
      type: date
    location:
      type: string(255)
    min_users_allowed:
      type: integer
    max_users_allowed:
      type: integer
    register_start_date:
      type: date
    register_end_date:
      type: date
    price:
      type: decimal
  inheritance:
    extends: Content
    type: column_aggregation
    keyField: type
CitizenAction:
  columns:
    author:
      type: string(150)
    action_date:
      type: date
    location:
      type: string(255)
    min_users_allowed:
      type: integer
    max_users_allowed:
      type: integer
    register_start_date:
      type: date
    register_end_date:
      type: date
  inheritance:
    extends: Content
    type: column_aggregation
    keyField: type
ContentHasRegion:
  columns:
    region_id:
      primary: true
      type: integer
      notnull: true
    content_id:
      primary: true
      type: integer
      notnull: true
  indexes:
    IX_ContentHasRegion_1:
      fields: [region_id, content_id]
      type: unique
  relations:
    Region:
      local: region_id
      foreign: id
    Content:
      local: content_id
      foreign: id
ContentHasCategory:
  columns:
    category_id:
      primary: true
      type: integer
      notnull: true
    content_id:
      primary: true
      type: integer
      notnull: true
  indexes:
    IX_ContentHasCategories_1:
      fields: [category_id, content_id]
      type: unique
  relations:
    Category:
      local: category_id
      foreign: id
    Content:
      local: content_id
      foreign: id
ActionHasUser:
  columns:
    action_id:
      primary: true
      type: integer
      notnull: true
    user_id:
      primary: true
      type: integer
      notnull: true
  indexes:
    IX_ActionHasUser_1:
      fields: [user_id, action_id]
      type: unique
  relations:
    Content:
      local: action_id
      foreign: id
    sfGuardUser:
      local: user_id
      foreign: id
actAs:
  Sluggable:
    unique: true
