sfGuardUserProfile:
  actAs:
    Timestampable: 
    Geographical: 
    JCroppable:
      images: [image]
  columns:
    user_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    gender:
      type: integer
    telephone:
      type: string(25)
    address:
      type: string(255)
    postal_code:
      type: string(10)
    location:
      type: string(150)
    province:
      type: string(150)
    country:
      type: string(150)
    web:
      type: string(255)
    about:
      type: clob
    subscription_email:
      default: 0
      type: boolean
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Profile
      onDelete: CASCADE
      type: one
      foreignType: one
      local: user_id
      foreign: id
    Categories:
      class: Category
      refClass: SubscriptionCategory
      local: user_id
      foreign: category_id
    Regions:
      class: Region
      refClass: SubscriptionRegion
      local: user_id
      foreign: region_id
Category:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    description:
      type: string(255)
  relations:
    Profiles:
      class: sfGuardUserProfile
      refClass: SubscriptionCategory
      local: category_id
      foreign: user_id
    Proposals:
      class: Content
      refClass: ContentHasCategory
      local: category_id
      foreign: content_id
Content:
  actAs:
    Timestampable: 
    Sluggable:
      alias: slug
      unique: true
      fields: [title]
      uniqueBy: [title]
    Searchable:
      fields: [title,body]
    Geographical: 
    JCroppable:
      images: [image]
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    body:
      type: clob
      notnull: true
    video:
      type: string(255)
    active:
      default: 1
      type: boolean
      notnull: true
    user_id:
      type: integer
      notnull: true
  relations:
    sfGuardUser:
      onDelete: CASCADE
      local: user_id
      foreign: id
    Categories:
      class: Category
      refClass: ContentHasCategory
      local: content_id
      foreign: category_id
    Regions:
      class: Region
      refClass: ContentHasRegion
      local: content_id
      foreign: region_id
Region:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    description:
      type: string(255)
  relations:
    Profiles:
      class: sfGuardUserProfile
      refClass: SubscriptionRegion
      local: region_id
      foreign: user_id
    Proposals:
      class: Content
      refClass: ContentHasRegion
      local: region_id
      foreign: content_id
ContentHasRegion:
  columns:
    content_id:
      primary: true
      type: integer
      notnull: true
    region_id:
      primary: true
      type: integer
      notnull: true
  relations:
    Content:
      onDelete: CASCADE
      local: content_id
      foreign: id
    Region:
      onDelete: CASCADE
      local: region_id
      foreign: id
ContentHasCategory:
  columns:
    content_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    category_id:
      primary: true
      unique: true
      type: integer
      notnull: true
  relations:
    Category:
      onDelete: CASCADE
      local: category_id
      foreign: id
    Content:
      onDelete: CASCADE
      local: content_id
      foreign: id
Response:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    body:
      type: clob
      notnull: true
    initiative_id:
      type: integer
  relations:
    Content:
      onDelete: CASCADE
      local: initiative_id
      foreign: id
ActionHasCategory:
  columns:
    category_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    action_id:
      primary: true
      unique: true
      type: integer
      notnull: true
  relations:
    Category:
      onDelete: CASCADE
      local: category_id
      foreign: id
VirtualMeeting:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    body:
      type: clob
      notnull: true
    user_id:
      type: integer
      notnull: true
    answers_start_date:
      type: date
      notnull: true
    answers_end_date:
      type: date
      notnull: true
  relations:
    sfGuardUser:
      onDelete: CASCADE
      local: user_id
      foreign: id
VirtualMeetingAnswer:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    answer:
      type: clob
      notnull: true
    opinion_id:
      type: integer
      notnull: true
    user_id:
      type: integer
      notnull: true
  relations:
    Opinion:
      onDelete: CASCADE
      local: opinion_id
      foreign: id
    sfGuardUser:
      onDelete: CASCADE
      local: user_id
      foreign: id
SubscriptionCategory:
  columns:
    user_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    category_id:
      primary: true
      unique: true
      type: integer
      notnull: true
  relations:
    sfGuardUserProfile:
      onDelete: CASCADE
      local: user_id
      foreign: user_id
    Category:
      onDelete: CASCADE
      local: category_id
      foreign: id
SubscriptionRegion:
  columns:
    user_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    region_id:
      primary: true
      unique: true
      type: integer
      notnull: true
  relations:
    sfGuardUserProfile:
      onDelete: CASCADE
      local: user_id
      foreign: user_id
    Region:
      onDelete: CASCADE
      local: region_id
      foreign: id
CitizenProposal:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    tip:
      type: clob
  inheritance:
    extends: Proposal
    type: concrete
GovermentProposal:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    publish_date:
      type: date
      notnull: true
  inheritance:
    extends: Proposal
    type: concrete
GovermentNew:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    publish_date:
      type: date
      notnull: true
  inheritance:
    extends: Content
    type: concrete
GovermentConsultation:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    start_date:
      type: date
      notnull: true
    end_date:
      type: date
  inheritance:
    extends: Proposal
    type: concrete
Action:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    author:
      type: string(150)
      notnull: true
    action_date:
      type: date
    location:
      type: string(255)
    min_users_allowed:
      type: integer
      notnull: true
    max_users_allowed:
      type: integer
    register_start_date:
      type: date
      notnull: true
    register_end_date:
      type: date
  inheritance:
    extends: Content
    type: concrete
  relations:
    Users:
      class: sfGuardUser
      refClass: ActionHasUser
      local: action_id
      foreign: user_id
Workshop:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    price:
      default: 0
      type: decimal
  inheritance:
    extends: Action
    type: concrete
CitizenAction:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
  inheritance:
    extends: Action
    type: concrete
ActionHasUser:
  columns:
    action_id:
      primary: true
      unique: true
      type: integer
      notnull: true
    user_id:
      primary: true
      unique: true
      type: integer
      notnull: true
  relations:
    Action:
      local: action_id
      foreign: id
    sfGuardUser:
      local: user_id
      foreign: id
Proposal:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
  inheritance:
    extends: Content
    type: concrete
actAs:
  Sluggable:
    unique: true
